name: 'download-vmlinux'
description: 'Download prebuilt vmlinux image'
inputs:
  kernel:
    description: 'kernel version'
    required: true
  arch:
    description: 'arch'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download prebuilt vmlinux
      shell: bash
      env:
        ARCH: ${{ inputs.arch }}
      run: |
        ${{ github.action_path }}/run.sh -k '${{ inputs.kernel }}'
